#!/usr/bin/env bash
# 按车道实时健康状况生成 Switchyard 路由配置。
# 全健康 → 正常三级路由;有车道挂掉 → 降级:
#   配了 TOGETHER_API_KEY → 挂掉的车道直接指向云端 API(不再碰本地大模型)
#   没配 key            → 指向幸存的本地车道,保证服务不中断
# 当前模式写入 logs/cluster_mode,供看门狗和控制台读取。
set -euo pipefail
cd "$(dirname "$0")/../.."

LARGE_PORT=${LARGE_PORT:-8001}
SMALL_PORT=${SMALL_PORT:-8002}
# 车道名由 inference 组件落盘(logs/lanes.env),本组件独立读取,不 import
LARGE_NAME=qwen3-32b-awq
SMALL_NAME=qwen3-1.7b-fp8
# shellcheck disable=SC1091
[ -f logs/lanes.env ] && . logs/lanes.env
[ -f .env ] && set -a && . ./.env && set +a

ok() { curl -sf --max-time 3 "http://127.0.0.1:$1/health" >/dev/null 2>&1; }
LARGE_OK=0; SMALL_OK=0
ok "$LARGE_PORT" && LARGE_OK=1
ok "$SMALL_PORT" && SMALL_OK=1

LARGE_URL="http://127.0.0.1:$LARGE_PORT/v1"
SMALL_URL="http://127.0.0.1:$SMALL_PORT/v1"

HAS_CLOUD=0
if [ -n "${TOGETHER_API_KEY:-}" ]; then
  HAS_CLOUD=1
  CLOUD_BASE_URL=${CLOUD_BASE_URL:-https://api.together.xyz/v1}
  CLOUD_MODEL=${CLOUD_MODEL:-Qwen/Qwen3-235B-A22B-Instruct-2507-tput}
  CLOUD_API_KEY=$TOGETHER_API_KEY
fi

# 每个车道解析到一个真实后端: "model base_url api_key"
resolve() { # resolve <想要的车道>
  local want=$1
  case "$want" in
    large) [ $LARGE_OK = 1 ] && { echo "$LARGE_NAME $LARGE_URL home"; return; } ;;
    small) [ $SMALL_OK = 1 ] && { echo "$SMALL_NAME $SMALL_URL home"; return; } ;;
  esac
  # 想要的车道不可用 → 云端优先,否则幸存车道
  if [ $HAS_CLOUD = 1 ]; then echo "$CLOUD_MODEL $CLOUD_BASE_URL $CLOUD_API_KEY"; return; fi
  if [ $LARGE_OK = 1 ]; then echo "$LARGE_NAME $LARGE_URL home"; return; fi
  if [ $SMALL_OK = 1 ]; then echo "$SMALL_NAME $SMALL_URL home"; return; fi
  echo "" # 全灭且无云端 key: 无路可走
}

read -r S_MODEL S_URL S_KEY <<< "$(resolve small)"
read -r L_MODEL L_URL L_KEY <<< "$(resolve large)"
if [ $HAS_CLOUD = 1 ]; then
  C_MODEL=$CLOUD_MODEL; C_URL=$CLOUD_BASE_URL; C_KEY=$CLOUD_API_KEY
else
  C_MODEL=$L_MODEL; C_URL=$L_URL; C_KEY=${L_KEY:-home}   # 假云端: 用大车道解析结果假冒
fi

if [ -z "$S_MODEL" ] || [ -z "$L_MODEL" ]; then
  echo "gen_routes: 本地车道全灭且未配 TOGETHER_API_KEY,无法生成可用路由" >&2
  echo "dead" > logs/cluster_mode
  exit 1
fi

if [ $LARGE_OK = 1 ] && [ $SMALL_OK = 1 ]; then MODE=normal
elif [ $LARGE_OK = 0 ] && [ $SMALL_OK = 0 ]; then MODE=degraded-all-cloud
elif [ $LARGE_OK = 0 ]; then MODE=$([ $HAS_CLOUD = 1 ] && echo degraded-large-cloud || echo degraded-large-small)
else MODE=$([ $HAS_CLOUD = 1 ] && echo degraded-small-cloud || echo degraded-small-large)
fi

{
  echo "# Generated by homed/gen_routes.sh — mode: $MODE ($(date '+%F %T'))"
  echo "defaults:"
  echo "  api_key: home"
  echo ""
  echo "routes:"
  if [ "$MODE" = normal ]; then
    # 正常: 先小后判,该升级就升级
    cat <<EOF
  auto:
    type: escalation_router
    weak:
      model: $S_MODEL
      base_url: $S_URL
    strong:
      model: $L_MODEL
      base_url: $L_URL
    judge:
      model: $S_MODEL
      base_url: $S_URL
      confirmations: 1
      disable_reasoning: true
      max_completion_tokens: 512
    fallback_target_on_evict: strong
EOF
  else
    # 降级: auto 不再分诊,直接指向 large 的解析结果(云端或幸存车道)
    cat <<EOF
  auto:
    type: model
    model: $L_MODEL
    base_url: $L_URL
    api_key: $L_KEY
EOF
  fi
  cat <<EOF

  small:
    type: model
    model: $S_MODEL
    base_url: $S_URL
    api_key: ${S_KEY:-home}

  large:
    type: model
    model: $L_MODEL
    base_url: $L_URL
    api_key: ${L_KEY:-home}

  cloud:
    type: model
    model: $C_MODEL
    base_url: $C_URL
    api_key: ${C_KEY:-home}
EOF
} > homed/router/routes.generated.yaml

mkdir -p logs
echo "$MODE" > logs/cluster_mode
echo "gen_routes: mode=$MODE (large_ok=$LARGE_OK small_ok=$SMALL_OK cloud_key=$HAS_CLOUD)"
