"""Route table generation for Switchyard 0.2 (YAML routing-profile bundle).

Semantics (design.md part 3 §3.2): each pool resolves to one healthy node; a pool with
no healthy node resolves to cloud (if a key is configured) else to a surviving pool.
`auto` is an escalation_router only when both weak and strong are live.
"""
from __future__ import annotations

import os
from dataclasses import dataclass

from ..paths import MODE_FILE, ROUTES_FILE, ROOT, ensure_dirs
from ..control.health import Assessment, mode as compute_mode
from ..control.registry import Node


@dataclass
class Target:
    model: str
    base_url: str
    api_key: str = "home"


@dataclass
class Cloud:
    enabled: bool
    model: str = ""
    base_url: str = ""
    api_key: str = ""


def cloud_from_env() -> Cloud:
    env = dict(os.environ)
    dotenv = ROOT / ".env"
    if dotenv.exists():
        for line in dotenv.read_text().splitlines():
            if "=" in line and not line.strip().startswith("#"):
                k, v = line.split("=", 1)
                env.setdefault(k.strip(), v.strip())
    key = env.get("TOGETHER_API_KEY", "")
    if not key:
        return Cloud(False)
    return Cloud(True,
                 env.get("CLOUD_MODEL", "Qwen/Qwen3-235B-A22B-Instruct-2507-tput"),
                 env.get("CLOUD_BASE_URL", "https://api.together.xyz/v1"),
                 key)


def _target(n: Node) -> Target:
    return Target(n.model, n.base_url)


def resolve(a: Assessment, cloud: Cloud) -> dict[str, Target | None]:
    """Resolve each public route to a concrete target."""
    strong = a.first("strong")
    weak = a.first("weak")
    cloud_t = Target(cloud.model, cloud.base_url, cloud.api_key) if cloud.enabled else None

    def fallback(prefer: Node | None) -> Target | None:
        if prefer:
            return _target(prefer)
        if cloud_t:
            return cloud_t
        for n in (strong, weak):
            if n:
                return _target(n)
        return None

    return {
        "strong": fallback(strong),
        "weak": fallback(weak),
        "cloud": cloud_t or fallback(strong) or fallback(weak),
        "long": _target(a.first("long")) if a.first("long") else None,
    }


def _model_route(name: str, t: Target) -> str:
    return (f"  {name}:\n    type: model\n    model: {t.model}\n"
            f"    base_url: {t.base_url}\n    api_key: {t.api_key}\n")


def render(a: Assessment, cloud: Cloud) -> tuple[str, str]:
    """Return (yaml_text, mode). Raises if nothing can serve."""
    r = resolve(a, cloud)
    m = compute_mode(a, cloud.enabled)
    if r["strong"] is None or r["weak"] is None:
        raise RuntimeError("no serving target: all local pools down and no cloud key")

    out = [f"# generated by homed.router.routes — mode: {m}", "defaults:", "  api_key: home", "", "routes:"]
    if m == "normal":
        w, s = r["weak"], r["strong"]
        out.append(
            "  auto:\n    type: escalation_router\n"
            f"    weak:\n      model: {w.model}\n      base_url: {w.base_url}\n"
            f"    strong:\n      model: {s.model}\n      base_url: {s.base_url}\n"
            f"    judge:\n      model: {w.model}\n      base_url: {w.base_url}\n"
            "      confirmations: 1\n      disable_reasoning: true\n      max_completion_tokens: 512\n"
            "    fallback_target_on_evict: strong\n"
        )
    else:
        out.append(_model_route("auto", r["strong"]))
    out.append(_model_route("small", r["weak"]))
    out.append(_model_route("large", r["strong"]))
    out.append(_model_route("cloud", r["cloud"]))
    if r["long"]:
        out.append(_model_route("long", r["long"]))
    return "\n".join(out) + "\n", m


def write(a: Assessment, cloud: Cloud | None = None) -> str:
    ensure_dirs()
    cloud = cloud or cloud_from_env()
    text, m = render(a, cloud)
    ROUTES_FILE.write_text(text)
    MODE_FILE.write_text(m)
    return m


def current_mode() -> str:
    return MODE_FILE.read_text().strip() if MODE_FILE.exists() else "unknown"
