#!/usr/bin/env python3
"""First-boot autotune: probe the GPU, pick a hardware profile, write config.

What big shops do with a platform team, we do with one script:
    1. `nvidia-smi` → GPU name + VRAM
    2. match a profile from config/profiles/ (largest models that fit,
       with KV-cache headroom)
    3. write `.env` (consumed by docker-compose) and `config/tandem.yaml`

Requires: pyyaml (`pip install pyyaml`). Run on the GPU host:
    python3 autotune/autotune.py [--dry-run] [--profile rtx4090]
"""
from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
PROFILES_DIR = ROOT / "config" / "profiles"


def probe_gpu() -> tuple[str, float]:
    """Return (gpu_name, vram_gb) for GPU 0."""
    out = subprocess.check_output(
        [
            "nvidia-smi",
            "--query-gpu=name,memory.total",
            "--format=csv,noheader,nounits",
        ],
        text=True,
    )
    first = out.strip().splitlines()[0]
    name, mem_mib = [part.strip() for part in first.split(",")]
    return name, float(mem_mib) / 1024


def load_profiles() -> list[dict]:
    profiles = []
    for path in sorted(PROFILES_DIR.glob("*.yaml")):
        with open(path, "r", encoding="utf-8") as fh:
            profile = yaml.safe_load(fh)
        profile["_file"] = path.name
        profiles.append(profile)
    return profiles


def match_profile(profiles: list[dict], vram_gb: float) -> dict | None:
    candidates = [
        p for p in profiles
        if p["match"]["min_vram_gb"] <= vram_gb <= p["match"].get("max_vram_gb", 10_000)
    ]
    if not candidates:
        return None
    # prefer the profile with the highest floor (i.e. the biggest models)
    return max(candidates, key=lambda p: p["match"]["min_vram_gb"])


def write_env(profile: dict) -> Path:
    large, small = profile["large"], profile["small"]
    lines = [
        "# Generated by autotune/autotune.py — edit config/profiles/*.yaml instead",
        f"LARGE_MODEL={large['model']}",
        f"LARGE_REVISION={large.get('revision', 'main')}",
        f"LARGE_QUANT={large.get('quantization', 'awq')}",
        f"LARGE_GPU_UTIL={large['gpu_mem_util']}",
        f"LARGE_MAX_LEN={large['max_model_len']}",
        f"SMALL_MODEL={small['model']}",
        f"SMALL_REVISION={small.get('revision', 'main')}",
        f"SMALL_QUANT={small.get('quantization', 'awq')}",
        f"SMALL_GPU_UTIL={small['gpu_mem_util']}",
        f"SMALL_MAX_LEN={small['max_model_len']}",
    ]
    env_path = ROOT / ".env"
    env_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return env_path


def write_gateway_config(profile: dict) -> Path:
    config = {
        "lanes": {
            "large": {
                "base_url": "http://vllm-large:8000/v1",
                "model": profile["large"]["model"],
                "revision": profile["large"].get("revision", "main"),
            },
            "small": {
                "base_url": "http://vllm-small:8000/v1",
                "model": profile["small"]["model"],
                "revision": profile["small"].get("revision", "main"),
            },
        },
    }
    config_path = ROOT / "config" / "tandem.yaml"
    if config_path.exists():
        print(f"  {config_path} already exists — leaving it alone")
        return config_path
    with open(config_path, "w", encoding="utf-8") as fh:
        yaml.safe_dump(config, fh, allow_unicode=True, sort_keys=False)
    return config_path


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true", help="probe and report only")
    parser.add_argument("--profile", help="force a profile by file name (without .yaml)")
    args = parser.parse_args()

    profiles = load_profiles()

    if args.profile:
        matched = next(
            (p for p in profiles if p["_file"] == f"{args.profile}.yaml"), None
        )
        if matched is None:
            print(f"no profile named {args.profile!r} in {PROFILES_DIR}")
            return 1
        print(f"forced profile: {matched['name']}")
    else:
        try:
            gpu_name, vram_gb = probe_gpu()
        except (OSError, subprocess.CalledProcessError) as exc:
            print(f"cannot probe GPU (is nvidia-smi available?): {exc}")
            print("hint: pass --profile <name> to skip probing")
            return 1
        print(f"detected: {gpu_name}, {vram_gb:.1f} GB VRAM")
        matched = match_profile(profiles, vram_gb)
        if matched is None:
            print("no profile fits this GPU — see config/profiles/ to add one")
            return 1
        print(f"matched profile: {matched['name']} ({matched['_file']})")

    large, small = matched["large"], matched["small"]
    print(f"  large lane: {large['model']} (mem util {large['gpu_mem_util']})")
    print(f"  small lane: {small['model']} (mem util {small['gpu_mem_util']})")

    if args.dry_run:
        return 0

    env_path = write_env(matched)
    config_path = write_gateway_config(matched)
    print(f"wrote {env_path}")
    print(f"wrote {config_path}")
    print("\nnext: docker compose up -d")
    return 0


if __name__ == "__main__":
    sys.exit(main())
