#!/usr/bin/env python3
"""First-boot autotune: probe the GPU, pick a hardware profile, write config.

What big shops do with a platform team, we do with one script:
    1. `nvidia-smi` → GPU name + VRAM
    2. match a profile from config/profiles/ (largest models that fit,
       with KV-cache headroom)
    3. write `.env` (consumed by docker-compose) and `config/tandem.yaml`

Requires: pyyaml (`pip install pyyaml`). Run on the GPU host:
    python3 autotune/autotune.py [--dry-run] [--profile rtx4090]
"""
from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
PROFILES_DIR = ROOT / "config" / "profiles"


def probe_gpu() -> tuple[str, float]:
    """Return (gpu_name, vram_gb) for GPU 0."""
    out = subprocess.check_output(
        [
            "nvidia-smi",
            "--query-gpu=name,memory.total",
            "--format=csv,noheader,nounits",
        ],
        text=True,
    )
    first = out.strip().splitlines()[0]
    name, mem_mib = [part.strip() for part in first.split(",")]
    return name, float(mem_mib) / 1024


def load_profiles() -> list[dict]:
    profiles = []
    for path in sorted(PROFILES_DIR.glob("*.yaml")):
        with open(path, "r", encoding="utf-8") as fh:
            profile = yaml.safe_load(fh)
        profile["_file"] = path.name
        profiles.append(profile)
    return profiles


def match_profile(profiles: list[dict], vram_gb: float) -> dict | None:
    candidates = [
        p for p in profiles
        if p["match"]["min_vram_gb"] <= vram_gb <= p["match"].get("max_vram_gb", 10_000)
    ]
    if not candidates:
        return None
    # prefer the profile with the highest floor (i.e. the biggest models)
    return max(candidates, key=lambda p: p["match"]["min_vram_gb"])


def _lane_lines(prefix: str, lane: dict) -> list[str]:
    return [
        f"{prefix}_MODEL={lane['model']}",
        f"{prefix}_REVISION={lane.get('revision', 'main')}",
        f"{prefix}_QUANT={lane.get('quantization', 'auto')}",
        f"{prefix}_GPU_UTIL={lane['gpu_mem_util']}",
        f"{prefix}_MAX_LEN={lane['max_model_len']}",
        f"{prefix}_KV_DTYPE={lane.get('kv_cache_dtype', 'auto')}",
        f"{prefix}_MAX_SEQS={lane.get('max_num_seqs', 16)}",
        f"{prefix}_MAX_BATCHED={lane.get('max_num_batched_tokens', 2048)}",
        f"{prefix}_EAGER={1 if lane.get('enforce_eager', True) else 0}",
    ]


def write_env(profile: dict) -> Path:
    lines = ["# Generated by autotune/autotune.py — edit config/profiles/*.yaml instead"]
    lines += _lane_lines("LARGE", profile["large"])
    lines += _lane_lines("SMALL", profile["small"])
    for key, value in profile.get("env", {}).items():
        lines.append(f"{key}={value}")
    env_path = ROOT / ".env"
    env_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return env_path


def write_gateway_config(profile: dict) -> Path:
    config = {
        "lanes": {
            "large": {
                "base_url": "http://vllm-large:8000/v1",
                "model": profile["large"]["model"],
                "revision": profile["large"].get("revision", "main"),
            },
            "small": {
                "base_url": "http://vllm-small:8000/v1",
                "model": profile["small"]["model"],
                "revision": profile["small"].get("revision", "main"),
            },
        },
    }
    config_path = ROOT / "config" / "tandem.yaml"
    if config_path.exists():
        print(f"  {config_path} already exists — leaving it alone")
        return config_path
    with open(config_path, "w", encoding="utf-8") as fh:
        yaml.safe_dump(config, fh, allow_unicode=True, sort_keys=False)
    return config_path


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true", help="probe and report only")
    parser.add_argument("--profile", help="force a profile by file name (without .yaml)")
    args = parser.parse_args()

    profiles = load_profiles()

    if args.profile:
        matched = next(
            (p for p in profiles if p["_file"] == f"{args.profile}.yaml"), None
        )
        if matched is None:
            print(f"no profile named {args.profile!r} in {PROFILES_DIR}")
            return 1
        print(f"forced profile: {matched['name']}")
    else:
        try:
            gpu_name, vram_gb = probe_gpu()
        except (OSError, subprocess.CalledProcessError) as exc:
            print(f"cannot probe GPU (is nvidia-smi available?): {exc}")
            print("hint: pass --profile <name> to skip probing")
            return 1
        print(f"detected: {gpu_name}, {vram_gb:.1f} GB VRAM")
        matched = match_profile(profiles, vram_gb)
        if matched is None:
            print("no profile fits this GPU — see config/profiles/ to add one")
            return 1
        print(f"matched profile: {matched['name']} ({matched['_file']})")

    large, small = matched["large"], matched["small"]
    print(f"  large lane: {large['model']} (mem util {large['gpu_mem_util']})")
    print(f"  small lane: {small['model']} (mem util {small['gpu_mem_util']})")

    if args.dry_run:
        return 0

    env_path = write_env(matched)
    config_path = write_gateway_config(matched)
    print(f"wrote {env_path}")
    print(f"wrote {config_path}")
    print("\nnext: docker compose up -d")
    return 0


if __name__ == "__main__":
    sys.exit(main())
